== histogram.cpp

=== Vídeo base
O vídeo base é uma gravação com OBS do videogame Session, editada para não ter tanto tempo morto do caminho entre as
áreas de cada cor.

=== Resolução

*O parágrafo a seguir partiu de uma péssima leitura do enunciado da primeira questão. Não foi feito equalizador algum de
histogramas, aqui foi um baita lapso.

Para esta tarefa, a maior parte do tempo foi tentando arranjar uma forma de passar a câmera virtual do OBS no Windows
para o WSL. Eventualmente instalei e compilei o próprio `histogram.cpp` no Windows (desagradável), para então não gostar
de como ficou o vídeo gravado ao vivo. Reescrevi para que o programa aceite o caminho/URI para o vídeo de entrada, e
mais algumas modificações para o tamanho da tela ser igual ao da entrada (provavelmente deixa o programa mais pesado,
mas sendo por vídeo gravado é mais tranquilo). No vídeo podemos ver minha perícia no skate em volta de três áreas, cada
uma mais próxima de um tom de cor e consequentemente com histogramas das respectivas cores mais puxado à direita em
relação ao demais. Infelizmente durante a gravação não chegou o período noturno, mas dá para ver o deslocamento conjunto
dos histogramas para valores mais altos na primeira área, onde a piscina azul claro puxa bastante as cores, e o
deslocamento à esquerda em geral a partir do meio do vídeo, onde as áreas tem mais sombra.

Para detecção de movimento decidi usar a norma L1 da diferença frame a frame do histograma vermelho dividida por um
terço dos pixels da imagem. A escolha por vermelho foi arbitrária, enquanto que a norma L1 foi pela existência da função
`cv::absdiff`. Inicialmente não havia divisão alguma do valor do histograma, então erroneamente "normalizei" pelo número
de pixeis ao invés do número de bins do histograma. Quando o valor, como de se esperar, ficou pequeno demais, eu ainda
não tinha percebido o erro na normalização, e pensei então que "se estou fazendo uma média por pixel mas os pixels
afetam três canais ao invés de um, eu deveria compensar para 1/3 deles". Ainda era um número baixo, mas mais
trabalhável, e depois de fazer uns ajustes finos cheguei no limiar de 0.065 usado no vídeo. Para alerta de movimento eu
aproveitei uma gambiarra pra sombreamento que fiz mês passado e estou usando uma mensagem no canto superior direito.
Incluí também a diferença enquanto fazia o ajuste fino e preferi por mantê-la.

video::NxfvAgecW2Q[youtube,align=center, width=600, height=600]

=== Íntegra dos códigos

.histogram.cpp
[%collapsible]
====
[source,c++, linenums]
----
include::histogram.cpp[]
----
====